name: test flow
on: push

#env:
#  CUCUMBER_PUBLISH_TOKEN:
#
jobs:
  build:
    name: Run test framework
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          java --version
          ls
          cd saucedemoSeleniumCucumberTests
          mvn clean test
